// export default {
//     ERROR: 'ERROR',
//     FILTER_BY_RANGE: 'FILTER_BY_RANGE',
//     FETCH_LOGS: 'FETCH_LOGS',
//     FILTER_NONE: 'FILTER_NONE',
//     FILTER_SUCCESS: 'FILTER_SUCCESS',
//     FILTER_FAILURE: 'FILTER_FAILURE',
//     REVALIDATE: 'REVALIDATE',
//     FILTER_NAT_TYPE1: 'FILTER_NAT_TYPE1',
//     FILTER_NAT_TYPE2: 'FILTER_NAT_TYPE2',
//     FILTER_OS_TYPE1: 'FILTER_OS_TYPE1',
//     FILTER_OS_TYPE2: 'FILTER_OS_TYPE2',
//     FILTER_COUNTRY_TYPE1: 'FILTER_COUNTRY_TYPE1',
//     FILTER_COUNTRY_TYPE2: 'FILTER_COUNTRY_TYPE2',
//     FILTER_BY_PROTOCOL: 'FILTER_BY_PROTOCOL',
//     FILTER_INCLUDE_PEER_ID: 'FILTER_INCLUDE_PEER_ID',
//     FILTER_EXCLUDE_PEER_ID: 'FILTER_EXCLUDE_PEER_ID',
//     NEW_LOG: 'NEW_LOG',
//     PROGRESS_COMPLETED: 'PROGRESS_COMPLETED',
//     UPDATE_PROGRESS: 'UPDATE_PROGRESS'
// };

export default {
    AnalyticalMethodID : "AnalyticalMethodID",
    TargetResidueType : "TargetResidueType",
    Reason : "Reason",
    LOD : "LOD",
    LOQ : "LOQ",
    MethodUsed : "MethodUsed",
    Is_TNTC_And_TFTC_Present: "Is_TNTC_and_TFTC_Present",
    TNTC_Limit:"TNTC_Limit",
    TFTC_Limit:"TFTC_Limit",
    SolventName : "SolventName",
    SolventQuantity : "SolventQuantity",
    DefaultRecovery : "DefaultRecovery",
    SolventVolume : "SolventVolume",
    IsRecoveryForSwabPresent : "IsRecoveryForSwabPresent",
    AddNewMoc : "AddNewMoc",
    SelectMoc : "SelectMoc",
    MocRecoveryPercent : "MocRecoveryPercent",
}