export default {
    AnalyticalMethodID : "AnalyticalMethodID",
    TargetResidueType : "TargetResidueType",
    Reason : "Reason",
    LOD : "LOD",
    LOQ : "LOQ",
    MethodUsed : "MethodUsed",
    Is_TNTC_And_TFTC_Present: "Is_TNTC_and_TFTC_Present",
    TNTC_Limit:"TNTC_Limit",
    TFTC_Limit:"TFTC_Limit",
    SolventName : "SolventName",
    SolventQuantity : "SolventQuantity",
    DefaultRecovery : "DefaultRecovery",
    SolventVolume : "SolventVolume",
    IsRecoveryForSwabPresent : "IsRecoveryForSwabPresent",
    AddNewMoc : "AddNewMoc",
    SelectMoc : "SelectMoc",
    MocRecoveryPercent : "MocRecoveryPercent",
}